# Created using wingetcreate 1.0.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: BraveSoftware.BraveBrowser
PackageVersion: 101.1.38.107
MinimumOSVersion: 10.0.0.0
ProductCode: BraveSoftware Brave-Browser
InstallerType: exe
Scope: user
InstallModes:
- silent
InstallerSwitches:
  Silent: ' '
  SilentWithProgress: ' '
UpgradeBehavior: install
Commands:
- brave
Protocols:
- http
- https
FileExtensions:
- htm
- html
- url
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.38.107/BraveBrowserStandaloneSilentSetup.exe
  InstallerSha256: F4C099B69658659A57F62FD6C3DD339C4DED6660E0747EDBBA8F0DA13982B336
- Architecture: x86
  InstallerType: exe
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.38.107/BraveBrowserStandaloneSilentSetup32.exe
  InstallerSha256: E66D9448F4731E15C2FAE9107EE578F36CBFE6E42FCCA4E57AEE4EFFC939684C
ManifestType: installer
ManifestVersion: 1.1.0

